### DISCUSSION TITLE
OFBuild, a tool to create projects.

### DISCUSSION THREAD

**Discussion by dimitre** [openframeworks/openFrameworks#7480] [Ideas]
I'm now building a tool, for personal usage at first, which can reproduce the project generation from a recipe.
I've thought about recipe formats and choose YAML instead of JSON, because it is easier to comment / uncomment blocks, there is no worring about trailing commas.

The idea is having a recipe in some project folder, that has all important information to rebuild a project if needed.
Similar to the projectGenerator front end it will invoke the projectGenerator commandLine to build everything, but getting information from a YML recipe.

Here is a sketch of the YAML file
```of.yml```
```yml
name: AeroFractal

ofpath: /Volumes/tool/ofw

addons:
- ofxAssimpModelLoader
- git@github.com:danomatika/ofxMidi.git
- git@github.com:dimitre/ofxMicroUI.git
- git@github.com:dimitre/ofxMicroUIMidiController.git
- git@github.com:astellato/ofxSyphon.git

platforms: ["macos", "ios"]

templates: ["vscode"]
```

Ideas are welcome

**Comment by dimitre** [comment]
Tool is already working with a projectGenerator branch.
I'm now working with the ability of checking out a specific branch, tag or commit.
wondering of how to call it, now in this example is "specific_addons" but I don't like very mych. ideas of a better name?

```yml
addons:
- ofxAssimpModelLoader
- ofxKinect
- ofxGui
- ofxOpenCV
- ofxNetwork
- ofxSvg
- ofxXmlSettings
- git@github.com:danomatika/ofxMidi.git
- git@github.com:dimitre/ofxMicroUI.git
- git@github.com:dimitre/ofxMicroUIMidiController.git

specific_addons:
- git: git@github.com:astellato/ofxSyphon.git
  branch: of_head
- git: git@github.com:dimitre/ofxTools.git
  branch: experimental
```

cc @2bbb
