### ISSUE TITLE
Actions - cancel in progress

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7132]
if we add in actions this block, soon after the "on" block, jobs are cancelled if a new commit is made on the same PR.
This is great to avoid spending unuseful CI minutes
```yaml
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true    
```

I've tested today in an experimental repository here
https://github.com/dimitre/ofConan/blob/main/.github/workflows/all.yml
