### ISSUE TITLE
[actions] build-linux64 tries to upload to ci.openframeworks.cc

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7834]
Maybe it is unnecessary now:
```yml
    - name: Upload Libs
      run: scripts/ci/upload_of_lib.sh;
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
```
