### ISSUE TITLE
Nightly builds aren't running nightly

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#8202]
@danoli3 did you change the behavior to only build when there have been changes to the repo?

When I look at the nightly actions they just say "Skipped"

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/0154a0b3-68f6-4d33-ac17-a553cd33efc8">

**Comment by dimitre** [comment]
there was a change by @danoli3 where this was removed from nightly and manual. should we put back?
```yml
on: 
  workflow_dispatch:
    inputs:
          release:
            description: 'release'     
            required: true
            default: 'nightly'
```
